export const data = [
	{
		img:require('../imgs/indeximg_05.jpg'),
		star:10086,
		share:10086,
		icon:require('../imgs/detailicon_26.png'),
		title:'简约 清新小户型 一居室',
	},
	{
		img:require('../imgs/indeximg_07.jpg'),
		star:324,
		share:1435,
		icon:require('../imgs/detailicon_29.png'),
		title:'简约 清新小户型 一居室',
	},
	{
		img:require('../imgs/indeximg_05.jpg'),
		star:124,
		share:456,
		icon:require('../imgs/detailicon_34.png'),
		title:'简约 清新小户型 一居室',
	},
	{
		img:require('../imgs/indeximg_07.jpg'),
		star:546,
		share:234,
		icon:require('../imgs/detailicon_36.png'),
		title:'简约 清新小户型 一居室',
	},
	{
		img:require('../imgs/indeximg_05.jpg'),
		star:646,
		share:234,
		icon:require('../imgs/detailicon_41.png'),
		title:'简约 清新小户型 一居室',
	},
	{
		img:require('../imgs/indeximg_07.jpg'),
		star:234,
		share:546,
		icon:require('../imgs/detailicon_40.png'),
		title:'简约 清新小户型 一居室',
	},
	{
		img:require('../imgs/indeximg_05.jpg'),
		star:456,
		icon:require('../imgs/detailicon_44.png'),
		share:546,
		title:'简约 清新小户型 一居室',
	},
	{
		img:require('../imgs/indeximg_07.jpg'),
		star:243,
		share:566,
		icon:require('../imgs/detailicon_40.png'),
		title:'简约 清新小户型 一居室',
	},
	{
		img:require('../imgs/indeximg_05.jpg'),
		star:10086,
		share:10086,
		icon:require('../imgs/detailicon_26.png'),
		title:'简约 清新小户型 一居室',
	},
	{
		img:require('../imgs/indeximg_07.jpg'),
		star:10086,
		share:10086,
		icon:require('../imgs/detailicon_29.png'),
		title:'简约 清新小户型 一居室',
	},
	{
		img:require('../imgs/indeximg_05.jpg'),
		star:10086,
		share:10086,
		icon:require('../imgs/detailicon_34.png'),
		title:'简约 清新小户型 一居室',
	},
	{
		img:require('../imgs/indeximg_07.jpg'),
		star:10086,
		share:10086,
		icon:require('../imgs/detailicon_36.png'),
		title:'简约 清新小户型 一居室',
	},
	{
		img:require('../imgs/indeximg_05.jpg'),
		star:10086,
		share:10086,
		icon:require('../imgs/detailicon_40.png'),
		title:'简约 清新小户型 一居室',
	},
	{
		img:require('../imgs/indeximg_07.jpg'),
		star:10086,
		share:10086,
		icon:require('../imgs/detailicon_41.png'),
		title:'简约 清新小户型 一居室',
	},
	{
		img:require('../imgs/indeximg_05.jpg'),
		star:10086,
		share:10086,
		icon:require('../imgs/detailicon_44.png'),
		title:'简约 清新小户型 一居室',
	},
	{
		img:require('../imgs/indeximg_07.jpg'),
		star:10086,
		share:10086,
		icon:require('../imgs/detailicon_34.png'),
		title:'简约 清新小户型 一居室',
	}
]